name: Bug report
description: Create a report to help us improve
title: "[Bug] "
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: Please verify that you've followed these steps
      options:
        - label: Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
          required: true

        - label: I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
          required: true

        - label: I have searched on the [issue tracker](……/) for a related issue.
          required: true

  - type: input
    attributes:
      label: JavTube Plugin Version
    validations:
      required: true

  - type: input
    attributes:
      label: JavTube Server Version
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other

  - type: textarea
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    attributes:
      label: JavTube Server
      description: Paste the command line parameters or environment below.

  - type: textarea
    attributes:
      label: Jellyfin/Emby Logs
      description: Paste the Jellyfin/Emby logs below.

  - type: textarea
    attributes:
      label: JavTube Server Logs
      description: Paste the javtube server logs below.

  - type: textarea
    attributes:
      label: How to Reproduce
      description: Steps to reproduce the behavior, if any.
