blank_issues_enabled: false

contact_links:
  - name: JavTube GitHub Wiki
    url: https://github.com/javtube/jellyfin-plugin-javtube/wiki
    about: Please see the wiki for configuration and examples
  - name: tun2socks GitHub Discussions
    url: https://github.com/javtube/jellyfin-plugin-javtube/discussions
    about: Ask questions and get help on GitHub Discussions
